import React, { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import styles from "../../styles/Blog.module.css";

const Slug = (props) => {
  const [blog, setBlog] = useState(props.blog);

  return (
    <div className={styles.container}>
      <Head>
        <title>iCoder - {blog?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next app, blog app" />
      </Head>

      <main className={styles.main}>
        <h2>{blog?.title}</h2>
        <p>{blog?.content}</p>
      </main>
    </div>
  );
};

export async function getServerSideProps(context) {
  // console.log("Context: ", context.query);
  // const router = useRouter();
  const { slug } = context.query;

  let data = await fetch(`http://localhost:3000/api/getblog?slug=${slug}`);
  let blog = await data.json();

  return {
    props: {
      blog,
    },
  };
}

export default Slug;
