import React, { useState } from "react";
import Head from "next/head";
import styles from "../../styles/Blog.module.css";
import * as fs from "fs";

const Slug = (props) => {
  const [blog, setBlog] = useState(props.blog);

  return (
    <div className={styles.container}>
      <Head>
        <title>iCoder - {blog?.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next app, blog app" />
      </Head>

      <main className={styles.main}>
        <h2>{blog?.title}</h2>
        <p>{blog?.content}</p>
      </main>
    </div>
  );
};

export async function getStaticPaths() {
  return {
    paths: [
      { params: { slug: "javaScript" } },
      { params: { slug: "php" } },
      { params: { slug: "python" } },
      { params: { slug: "react" } },
    ],
    fallback: true,
  };
}

export async function getStaticProps(context) {
  // console.log("Context: ", context.query);
  // const router = useRouter();
  console.log("Context", context);
  const { slug } = context.params;

  let blog = await fs.promises.readFile(`blogdata/${slug}.json`, "utf-8");

  // let data = await fetch(`http://localhost:3000/api/getblog?slug=${slug}`);
  // let blog = await data.json();

  return {
    props: {
      blog: JSON.parse(blog),
    },
  };
}

export default Slug;
