import React, { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Blog.module.css";
import * as fs from "fs";

const Blog = (props) => {
  console.log(props);
  const [blogs, setBlogs] = useState(props.allBlogs);

  return (
    <div className={styles.container}>
      <Head>
        <title>iCoder - Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next app, blog app" />
      </Head>

      <main className={styles.main}>
        <div className={styles.blogs}>
          {blogs.map((blog, index) => {
            return (
              <div key={index} className={styles.blogItem}>
                <Link href={`/blogpost/${blog.slug}`}>
                  <h2>{blog.title}</h2>
                </Link>
                <p>
                  {blog.content.substr(0, 250) + "... "}
                  <Link href={`/blogpost/${blog.slug}`}>read more</Link>
                </p>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
};

export async function getStaticProps(context) {
  // let data = await fetch("http://localhost:3000/api/blogs");
  // let allBlogs = await data.json();

  let data = await fs.promises.readdir("blogdata");
  let myFile;
  let allBlogs = [];
  for (let i = 0; i < data.length; i++) {
    const item = data[i];
    myFile = await fs.promises.readFile("blogdata/" + item, "utf-8");
    allBlogs.push(JSON.parse(myFile));
  }

  return {
    props: {
      allBlogs,
    },
  };
}

export default Blog;
