import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Blog.module.css";

const Blog = () => {
  const [blogs, setBlogs] = useState([]);

  useEffect(() => {
    console.log("useEffect is running.");
    fetch("http://localhost:3000/api/blogs")
      .then((items) => {
        // console.log("Items: ", items);
        return items.json();
      })
      .then((data) => {
        // console.log("Data: ", data);
        setBlogs(data);
      });
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>iCoder - Blogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next app, blog app" />
      </Head>

      <main className={styles.main}>
        <div className={styles.blogs}>
          {blogs.map((blog, index) => {
            return (
              <div key={index} className={styles.blogItem}>
                <Link href={`/blogpost/${blog.slug}`}>
                  <h2>{blog.title}</h2>
                </Link>
                <p>
                  {blog.content.substr(0, 250) + "... "}
                  <Link href={`/blogpost/${blog.slug}`}>read more</Link>
                </p>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
};

export default Blog;
