import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [blogs, setBlogs] = useState([]);

  useEffect(() => {
    console.log("useEffect is running.");
    fetch("http://localhost:3000/api/blogs")
      .then((items) => {
        return items.json();
      })
      .then((data) => {
        setBlogs(data);
      });
  }, []);

  return (
    <div>
      <Head>
        <title>iCoder App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next app, blog app" />
      </Head>

      <main className={styles.main}>
        <div className={styles.hero}>
          <h1 className={styles.title}>iCoder Blog App</h1>
          <p className={styles.description}>
            A blog for developers to learn new frameworks and technologies.
          </p>
        </div>

        <div className={styles.container}>
          <h4 className={styles.text}>All Blogs</h4>
          <div className={styles.blogs}>
            {blogs.map((blog, index) => {
              return (
                <div key={index} className={styles.blogItem}>
                  <Link href={`/blogpost/${blog.slug}`}>
                    <h2>{blog.title}</h2>
                  </Link>
                  <p>
                    {blog.content.substr(0, 250) + "... "}
                    <Link href={`/blogpost/${blog.slug}`}>read more</Link>
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </div>
  );
}
